### ISSUE TITLE
Question about use diffusion models for image classification

### ISSUE THREAD

**Issue by mabaisen** [soumik-kanad/diffssl#2]
Hello, thank you for putting up such a great job.
But I‘m confused about using diffusion models for image classification. The diffusion model predicts noise, why its intermediate features can be used for classification?

**Comment by soumik-kanad** [comment]
Hi, that is a good question. I would suggest that you take a look at our paper's Section 2. 

In short, the diffusion model is trained to predict noise given the noisy image, so that it can be removed from the image. But it needs to know the structure in the image to be able to tell how the noise to be removed would look like. We see in Fig 3 (middle) that blocks just after the UNet bottleneck have the best performance. The later layer's performance is worse because it needs to convert the signal into noise, but there is a sweet spot where it understands the structures the best (block 24 in this case, where bottleneck is block 19).

**Comment by mabaisen** [comment]
> Hi, that is a good question. I would suggest that you take a look at our paper's Section 2.
> 
> In short, the diffusion model is trained to predict noise given the noisy image, so that it can be removed from the image. But it needs to know the structure in the image to be able to tell how the noise to be removed would look like. We see in Fig 3 (middle) that blocks just after the UNet bottleneck have the best performance. The later layer's performance is worse because it needs to convert the signal into noise, but there is a sweet spot where it understands the structures the best (block 24 in this case, where bottleneck is block 19).

Thank you for your answer, i understand.
