### ISSUE TITLE
Use of Semi-Supervised Learning

### ISSUE THREAD

**Issue by YonghanLU** [soumik-kanad/diffssl#7]
I am very interested semi-supervised learning part of your work. So I want to know how to run the semi-supervised training? Thanks for your great work.

**Comment by soumik-kanad** [comment]
First, create your 1% or 10% ImageNet subsets using [preprocess_datasets.py](https://github.com/soumik-kanad/diffssl/blob/main/datasets/imagenet_subsets/process_dataset.py). 

Then you can use the same scripts like [scripts/fusion.sh](https://github.com/soumik-kanad/diffssl/blob/main/scripts/fusion.sh) or [scripts/feedback.sh](https://github.com/soumik-kanad/diffssl/blob/main/scripts/fusion.sh). But you need to update the following flags:

- `--data_dir` and `--val_data_dir` to the newly created subset paths. 
- `--mode=finetune` instead of `--mode=freeze`
- `--lr` may need to be tuned and `--batch_size` needs to be updated to whatever fits on your GPU. Here are our settings:
  - 1% DifFormer: `--lr=1e-2 --batch_size=2`
  - 10% DifFormer: `--lr=1e-2 --batch_size=2`
  - 1% DifFeed: `--lr=1e-2 --batch_size=4`
  - 10% DifFeed: `--lr=1e-2 --batch_size=4`
